// AUTO-GENERATED by scripts/generate-reserved-slugs.mjs.
// Do not edit by hand — edit server/internal/handler/reserved_slugs.json
// and run `pnpm generate:reserved-slugs`.

/**
 * Slugs reserved because they collide with frontend top-level routes,
 * platform features, or web standards.
 *
 * Single source of truth: `server/internal/handler/reserved_slugs.json`.
 * The Go backend embeds that JSON; this file is regenerated from it.
 *
 * Convention for new global routes (CLAUDE.md): use a single word
 * (`/login`, `/inbox`) or `/{noun}/{verb}` (`/workspaces/new`). Hyphenated
 * root-level word groups (`/new-workspace`, `/create-team`) collide with
 * common user workspace names — see PR for full discussion.
 */
export const RESERVED_SLUGS: ReadonlySet<string> = new Set([
  // Pre-workspace frontend routes
  // Top-level routes in apps/web/app/ that exist before the user enters a
  // workspace.
  "login",
  "auth",

  // Backend API / health routes
  // `/api` covers all API traffic; `/ws` is the WebSocket endpoint; `/uploads`
  // serves attachments; `/health`, `/readyz`, `/healthz` are backend
  // health-check paths.
  "api",
  "ws",
  "uploads",
  "health",
  "healthz",
  "readyz",

  // Workspace route segments
  // Reserving each segment name prevents `/{slug}/{view}` from being ambiguous —
  // e.g. a workspace named `issues` would make `/issues/abc` mean two things.
  // `members` is kept even though the members tab is removed, to prevent it from
  // being chosen as a workspace slug.
  "agents",
  "attachments",
  "autopilots",
  "decisions",
  "inbox",
  "initiatives",
  "issues",
  "live",
  "members",
  "my-issues",
  "runtimes",
  "settings",
  "skills",
  "usage",
]);

export function isReservedSlug(slug: string): boolean {
  return RESERVED_SLUGS.has(slug);
}
